### ISSUE TITLE
help with the XMPP API in Windows

### ISSUE THREAD

**Issue by israel-gonzalezmedina** [SAMA-Communications/sama-server#128]
Hello. I trying to run the code for development with the assistance of
https://medium.com/sama-communications/deploying-sama-chat-server-stack-a-comprehensive-guide-294ddb9a2d78
however, I am getting the error:
 ENOENT: no such file or directory, open '.....\sama-server\APIs\XMPP\index.js']

any help with this?

**Comment by IgorKhomenko** [comment]
@israel-gonzalezmedina which NodeJS version you use? It should be 18

Is this error ocures after you run `npm run start` ?

I just re-tested it, cloned the fresh repo and did `npm i` and `npm run start` and it works just smooth. Any other commands you ran in addition?

**Comment by israel-gonzalezmedina** [comment]
thanks for the quick reply @IgorKhomenko . BTW congrats on such a nice project. My node version is v18.19.0.
The error occurs after `npm run start`.
I am using docker on windows.
The error is about the non-existence of the path
<sama-server-directory>\APIs\XMPP\index.js
Ideed the file didn't download with the git clone operation. When try to access the API/XMPP on the Github website (https://github.com/SAMA-Communications/xmpp-adapter/tree/e2b44c956568b88c0eccc593a7455b3add2ba492) I get a 404.

**Comment by israel-gonzalezmedina** [comment]
it work. I will change the title so it can helps others.
Thanks

**Comment by israel-gonzalezmedina** [comment]
it works!!. I will change the title so it can helps others.
Thanks
