### ISSUE TITLE
License

### ISSUE THREAD

**Issue by claytongulick** [SAMA-Communications/sama-server#133]
Hi! Very cool project, I'm interested in pitching in.

One thing I noticed is a discrepancy between the LICENSE file and the specified license in package.json, one is GPL and the other AGPL.

Could you clarify your license?

Thanks!!

**Comment by IgorKhomenko** [comment]
Hey @claytongulick 
thanks for pointing the diff 👍 

The package.json is now aligned with the LICENSE file (GPL-3.0)
