### ISSUE TITLE
Documentation for windows: Detailed steps to setup env creds

### ISSUE THREAD

**Issue by dhruvanwd** [SAMA-Communications/sama-server#49]
Documentation for windows: Detailed steps to setup environment variables. 
please provide detailed step by step guide to setup development server on local windows machine.

**Comment by IgorKhomenko** [comment]
@dhruvanwd thanks for raising this
Will get back to you during next couple days with Windows guide

**Comment by IgorKhomenko** [comment]
@dhruvanwd we have updated the Development guide here https://github.com/SAMA-Communications/sama-server/blob/main/README.md#development

and also updated https://github.com/SAMA-Communications/sama-server/blob/main/.env.example

Please let me know if it works for you
