### ISSUE TITLE
Lacks of exception handling

### ISSUE THREAD

**Issue by TepuVilla** [SAMA-Communications/sama-server#70]
Hi! First of all great job, this is an awesome project! 🥇 
Then I would like to point some major bugs (I'm not a NodeJS expert that's why I'm pointing this out without the solution, sorry for this).

If you got for example:
`{
  "request": {
    "user_create": {
      login: "user",
      "password": "user_paswword"
    },
    "id": "421cda83-7f49-45a9-81e8-5f83cfa0533c"
  }
}`
Which is an invalid JSON because it lacks the "" on login, then the application will crash, this will be a problem if someone tries to attack the server as it'll make the service unavailable.

I'm not sure if it's lacking on more exceptions, and once again sorry for requesting this without a PR.

**Comment by IgorKhomenko** [comment]
@TepuVilla appreciate for the provided feedback! 🥇 

Probably returning something like would be a good option

```
{
  "response": {
    "id": "421cda83-7f39-45a9-81e8-5f83cfa0733c",
    "error": {
      "status": 400,
      "message": "Bad request - invalid data format"
    }
  }
} 
```

will take care

**Comment by IgorKhomenko** [comment]
Implemented and merged here https://github.com/SAMA-Communications/sama-server/pull/71
