### ISSUE TITLE
multiple authentication method

### ISSUE THREAD

**Issue by yadav-saurabh** [SAMA-Communications/sama-server#97]
Hi, 
I liked the project, can you guys support other types of authentication?

I would like to have a way to use Keycloak, let me know if I can work on this and can submit a PR.

thanks.

**Comment by IgorKhomenko** [comment]
Hey @yadav-saurabh 

Thank you for your interest in the project 

We have a bunch of other things for the current roadmap, 
if you could work at Keycloak on your own and submit a PR - that would be awesome, happy to review it 👍

**Comment by yadav-saurabh** [comment]
thanks

will work on it and submit a PR
